"""create ingredients and recipe_ingredients tables

Revision ID: 41399cab164a
Revises: 98f204655279
Create Date: 2026-09-17 18:59:02.048593

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41399cab164a"
down_revision: str | Sequence[str] | None = "98f204655279"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.CheckConstraint(
            "length(trim(name)) >= 1", name=op.f("ck_ingredients_name_not_blank")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingredients")),
        sa.UniqueConstraint("name", name=op.f("uq_ingredients_name")),
    )
    op.create_table(
        "recipe_ingredients",
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "unit",
            sa.Enum(
                "g",
                "ml",
                "個",
                "大さじ",
                "小さじ",
                name="unit_values",
                native_enum=False,
                create_constraint=True,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "length(note) <= 1000", name=op.f("ck_recipe_ingredients_note_length_lte")
        ),
        sa.CheckConstraint(
            "note IS NULL OR length(trim(note)) >= 1",
            name=op.f("ck_recipe_ingredients_note_not_blank"),
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_recipe_ingredients_quantity_gt")
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
            name=op.f("fk_recipe_ingredients_ingredient_id_ingredients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_recipe_ingredients_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "recipe_id", "ingredient_id", name=op.f("pk_recipe_ingredients")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipe_ingredients")
    op.drop_table("ingredients")
    # ### end Alembic commands ###
