"""add step table

Revision ID: b226c1122548
Revises: d03de9676337
Create Date: 2026-09-11 05:52:58.355298

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b226c1122548"
down_revision: str | Sequence[str] | None = "d03de9676337"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("step_no", sa.SmallInteger(), nullable=False),
        sa.Column("instruction", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "length(instruction) <= 1000", name=op.f("ck_steps_instruction_length_lte")
        ),
        sa.CheckConstraint(
            "length(trim(instruction)) >= 1",
            name=op.f("ck_steps_instruction_not_blank"),
        ),
        sa.CheckConstraint("step_no >= 1", name=op.f("ck_steps_step_no_gte")),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_steps_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_steps")),
        sa.UniqueConstraint(
            "recipe_id", "step_no", name=op.f("uq_steps_recipe_id_step_no")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("steps")
    # ### end Alembic commands ###
