"""add nutrition table

Revision ID: bb176e0c442c
Revises: 41399cab164a
Create Date: 2026-09-23 16:36:18.700901

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb176e0c442c"
down_revision: str | Sequence[str] | None = "41399cab164a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.CheckConstraint(
            "length(trim(name)) >= 1", name=op.f("ck_tags_name_length_gte")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("name", name=op.f("uq_tags_name")),
    )
    op.create_table(
        "nutritions",
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("calories", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("protein_g", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("fat_g", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("carb_g", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.CheckConstraint("calories >= 0", name=op.f("ck_nutritions_calories_gte")),
        sa.CheckConstraint("carb_g >= 0", name=op.f("ck_nutritions_carb_g_gte")),
        sa.CheckConstraint("fat_g >= 0", name=op.f("ck_nutritions_fat_g_gte")),
        sa.CheckConstraint("protein_g >= 0", name=op.f("ck_nutritions_protein_g_gte")),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_nutritions_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("recipe_id", name=op.f("pk_nutritions")),
    )
    op.create_table(
        "recipe_tags",
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_recipe_tags_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            name=op.f("fk_recipe_tags_tag_id_tags"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("recipe_id", "tag_id", name=op.f("pk_recipe_tags")),
    )
    op.drop_constraint(
        op.f("fk_recipe_ingredients_ingredient_id_ingredients"),
        "recipe_ingredients",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_recipe_ingredients_ingredient_id_ingredients"),
        "recipe_ingredients",
        "ingredients",
        ["ingredient_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_recipe_ingredients_ingredient_id_ingredients"),
        "recipe_ingredients",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_recipe_ingredients_ingredient_id_ingredients"),
        "recipe_ingredients",
        "ingredients",
        ["ingredient_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_table("recipe_tags")
    op.drop_table("nutritions")
    op.drop_table("tags")
    # ### end Alembic commands ###
