"""create users and recipes tables

Revision ID: d03de9676337
Revises:
Create Date: 2026-09-07 18:39:42.007702

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d03de9676337"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "email ~ '^[^@]+@[^@]+\\.[^@]+$'",
            name=op.f("ck_users_email_validation_loose"),
        ),
        sa.CheckConstraint(
            "bio IS NULL or length(trim(bio)) >= 1", name=op.f("ck_users_bio_not_blank")
        ),
        sa.CheckConstraint(
            "email = lower(email)", name=op.f("ck_users_email_lowercase")
        ),
        sa.CheckConstraint("length(bio) <= 1000", name=op.f("ck_users_bio_length_lte")),
        sa.CheckConstraint(
            "length(trim(name)) >= 2", name=op.f("ck_users_name_length_gte")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("servings", sa.Integer(), nullable=False),
        sa.Column("cook_time_min", sa.Integer(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum(
                "easy",
                "normal",
                "hard",
                name="difficulty_values",
                native_enum=False,
                create_constraint=True,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("source", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("cook_time_min >= 1", name=op.f("ck_recipes_cook_time_gte")),
        sa.CheckConstraint(
            "description IS NULL OR length(trim(description)) >= 1",
            name=op.f("ck_recipes_description_not_blank"),
        ),
        sa.CheckConstraint(
            "length(description) <= 5000",
            name=op.f("ck_recipes_description_length_lte"),
        ),
        sa.CheckConstraint(
            "length(trim(title)) >= 1", name=op.f("ck_recipes_title_gte")
        ),
        sa.CheckConstraint("servings >= 1", name=op.f("ck_recipes_servings_gte")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_recipes_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipes")),
        sa.UniqueConstraint("user_id", "title", name=op.f("uq_recipes_user_id_title")),
    )
    op.create_index(
        op.f("ix_recipes_source"),
        "recipes",
        ["source"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_recipes_source"), table_name="recipes", postgresql_using="gin"
    )
    op.drop_table("recipes")
    op.drop_table("users")
    # ### end Alembic commands ###
